definitions:
  webserver.DatasetControllerIngestDataset200JSONResponse:
    properties:
      ingestId:
        description: IngestId The unique ingestion id of the dataset.
        type: string
      status:
        description: Status The status of the ingestion. Can be used to send a message
          back to the ui.
        type: string
    type: object
  webserver.DatasetControllerIngestDatasetJSONRequestBody:
    properties:
      metaData:
        description: MetaData The metadata of the dataset.
        type: string
    type: object
  webserver.DatasetControllerIngestDatasetRequestObject:
    properties:
      body:
        $ref: '#/definitions/webserver.DatasetControllerIngestDatasetJSONRequestBody'
    type: object
  webserver.IngestorUiGetTransferItem:
    properties:
      status:
        type: string
      transferId:
        type: string
    type: object
  webserver.OtherControllerGetVersion200JSONResponse:
    properties:
      version:
        description: Version Version of the ingestor.
        type: string
    type: object
  webserver.TransferControllerDeleteTransfer200JSONResponse:
    properties:
      ingestId:
        description: IngestId Ingestion id to abort the ingestion
        type: string
      status:
        description: Status New status of the ingestion.
        type: string
    type: object
  webserver.TransferControllerDeleteTransferJSONRequestBody:
    properties:
      ingestId:
        description: IngestId Ingestion id to abort the ingestion
        type: string
    type: object
  webserver.TransferControllerDeleteTransferRequestObject:
    properties:
      body:
        $ref: '#/definitions/webserver.TransferControllerDeleteTransferJSONRequestBody'
    type: object
  webserver.TransferControllerGetTransfer200JSONResponse:
    properties:
      total:
        description: Total Total number of transfers.
        type: integer
      transfers:
        items:
          $ref: '#/definitions/webserver.IngestorUiGetTransferItem'
        type: array
    type: object
info:
  contact:
    email: spencer.bliven@psi.ch
    name: SwissOpenEM
    url: https://swissopenem.github.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /callback:
    get:
      description: For handling the authorization code received from the OIDC provider
      parameters:
      - description: OAuth2 authorization code
        in: query
        name: code
        required: true
        type: string
      - description: OAuth2 state param
        in: query
        name: state
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "302":
          description: Found
          headers:
            Location:
              description: goes to '/'
              type: string
        "400":
          description: request error
          schema:
            type: string
        "500":
          description: server error
          schema:
            type: string
      tags:
      - authentication
  /datasets:
    post:
      consumes:
      - application/json
      description: Ingest a new dataset
      parameters:
      - description: mainly contains the dataset metadata
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/webserver.DatasetControllerIngestDatasetRequestObject'
      produces:
      - json      text/plain
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/webserver.DatasetControllerIngestDataset200JSONResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - datasets
  /logout:
    get:
      description: Ends user session by deleting the session cookie.
      responses:
        "302":
          description: Found
          headers:
            Location:
              description: goes to '/'
              type: string
        "500":
          description: can't delete cookie
          schema:
            type: string
      tags:
      - authentication
  /transfer:
    delete:
      consumes:
      - application/json
      description: Cancel a data transfer
      parameters:
      - description: it contains the id to cancel
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/webserver.TransferControllerDeleteTransferRequestObject'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/webserver.TransferControllerDeleteTransfer200JSONResponse'
        "400":
          description: Bad Request
          schema:
            type: string
      tags:
      - transfer
    get:
      description: '"Get list of transfers. Optional use the transferId parameter
        to only get one item."'
      parameters:
      - description: page of transfers
        in: query
        name: page
        type: integer
      - description: number of elements per page
        in: query
        name: pageSize
        type: integer
      - description: get specific transfer by id
        in: query
        name: transferId
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: returns the list of transfers
          schema:
            $ref: '#/definitions/webserver.TransferControllerGetTransfer200JSONResponse'
        "400":
          description: the request is invalid
          schema:
            type: string
      tags:
      - transfer
  /version:
    get:
      description: Get the used ingestor version
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/webserver.OtherControllerGetVersion200JSONResponse'
      tags:
      - other
swagger: "2.0"
