// Package extglobusservice provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package extglobusservice

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// FileToTransfer the file to transfer as part of a transfer request
type FileToTransfer struct {
	// IsSymlink specifies whether this file is a symlink
	IsSymlink bool `json:"isSymlink"`

	// Path the path of the file, it has to be relative to the dataset source folder
	Path string `json:"path"`
}

// GeneralErrorResponse defines model for GeneralErrorResponse.
type GeneralErrorResponse struct {
	// Details further details, debugging information
	Details *string `json:"details,omitempty"`

	// Message the error message
	Message *string `json:"message,omitempty"`
}

// PostTransferTaskJSONBody defines parameters for PostTransferTask.
type PostTransferTaskJSONBody struct {
	FileList *[]FileToTransfer `json:"fileList,omitempty"`
}

// PostTransferTaskParams defines parameters for PostTransferTask.
type PostTransferTaskParams struct {
	// SourceFacility the identifier name of the source facility
	SourceFacility string `form:"sourceFacility" json:"sourceFacility"`

	// DestFacility the path in the destination collection to use for the transfer
	DestFacility string `form:"destFacility" json:"destFacility"`

	// ScicatPid the pid of the dataset being transferred
	ScicatPid string `form:"scicatPid" json:"scicatPid"`

	// CollectionRootPath Path to the root of the globus collection on the source facility
	CollectionRootPath string `form:"collectionRootPath" json:"collectionRootPath"`

	// AutoArchive start archive job after successful transfer
	AutoArchive *bool `form:"autoArchive,omitempty" json:"autoArchive,omitempty"`
}

// DeleteTransferTaskParams defines parameters for DeleteTransferTask.
type DeleteTransferTaskParams struct {
	// Delete Enables/disables deleting from scicat job system. By default, it's disabled (false).
	Delete *bool `form:"delete,omitempty" json:"delete,omitempty"`
}

// PostTransferTaskJSONRequestBody defines body for PostTransferTask for application/json ContentType.
type PostTransferTaskJSONRequestBody PostTransferTaskJSONBody

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// PostTransferTaskWithBody request a transfer task
	//
	// It allows for requesting transfer tasks against a SciCat token. It uses the service account configured with the service's instance
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /transfer (the `PostTransferTask` operationId).
	PostTransferTaskWithBody(ctx context.Context, params *PostTransferTaskParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostTransferTask request a transfer task
	//
	// It allows for requesting transfer tasks against a SciCat token. It uses the service account configured with the service's instance
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /transfer (the `PostTransferTask` operationId).
	PostTransferTask(ctx context.Context, params *PostTransferTaskParams, body PostTransferTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteTransferTask cancels and/or deletes transfer entry
	//
	// allows the user to cancel a transfer and/or delete the job from the scicat job system.
	//
	// Corresponds with DELETE /transfer/{scicatJobId} (the `DeleteTransferTask` operationId).
	DeleteTransferTask(ctx context.Context, scicatJobId string, params *DeleteTransferTaskParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetVersion get SciCat Globus Proxy version
	//
	// returns the current version of the proxy.
	//
	// Corresponds with GET /version (the `GetVersion` operationId).
	GetVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// PostTransferTaskWithBody request a transfer task
//
// It allows for requesting transfer tasks against a SciCat token. It uses the service account configured with the service's instance
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /transfer (the `PostTransferTask` operationId).
func (c *Client) PostTransferTaskWithBody(ctx context.Context, params *PostTransferTaskParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTransferTaskRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostTransferTask request a transfer task
//
// It allows for requesting transfer tasks against a SciCat token. It uses the service account configured with the service's instance
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /transfer (the `PostTransferTask` operationId).
func (c *Client) PostTransferTask(ctx context.Context, params *PostTransferTaskParams, body PostTransferTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTransferTaskRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteTransferTask cancels and/or deletes transfer entry
//
// allows the user to cancel a transfer and/or delete the job from the scicat job system.
//
// Corresponds with DELETE /transfer/{scicatJobId} (the `DeleteTransferTask` operationId).
func (c *Client) DeleteTransferTask(ctx context.Context, scicatJobId string, params *DeleteTransferTaskParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteTransferTaskRequest(c.Server, scicatJobId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetVersion get SciCat Globus Proxy version
//
// returns the current version of the proxy.
//
// Corresponds with GET /version (the `GetVersion` operationId).
func (c *Client) GetVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetVersionRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostTransferTaskRequest calls the generic PostTransferTask builder with application/json body
func NewPostTransferTaskRequest(server string, params *PostTransferTaskParams, body PostTransferTaskJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostTransferTaskRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPostTransferTaskRequestWithBody constructs an http.Request for the PostTransferTask method, with any body, and a specified content type
func NewPostTransferTaskRequestWithBody(server string, params *PostTransferTaskParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/transfer")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sourceFacility", params.SourceFacility, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "destFacility", params.DestFacility, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "scicatPid", params.ScicatPid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "collectionRootPath", params.CollectionRootPath, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if params.AutoArchive != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "autoArchive", *params.AutoArchive, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteTransferTaskRequest constructs an http.Request for the DeleteTransferTask method
func NewDeleteTransferTaskRequest(server string, scicatJobId string, params *DeleteTransferTaskParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "scicatJobId", scicatJobId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/transfer/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Delete != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "delete", *params.Delete, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetVersionRequest constructs an http.Request for the GetVersion method
func NewGetVersionRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/version")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// PostTransferTaskWithBodyWithResponse request a transfer task
	//
	// It allows for requesting transfer tasks against a SciCat token. It uses the service account configured with the service's instance
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /transfer (the `PostTransferTask` operationId).
	PostTransferTaskWithBodyWithResponse(ctx context.Context, params *PostTransferTaskParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTransferTaskResponse, error)

	// PostTransferTaskWithResponse request a transfer task
	//
	// It allows for requesting transfer tasks against a SciCat token. It uses the service account configured with the service's instance
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /transfer (the `PostTransferTask` operationId).
	PostTransferTaskWithResponse(ctx context.Context, params *PostTransferTaskParams, body PostTransferTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTransferTaskResponse, error)

	// DeleteTransferTaskWithResponse cancels and/or deletes transfer entry
	//
	// allows the user to cancel a transfer and/or delete the job from the scicat job system.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /transfer/{scicatJobId} (the `DeleteTransferTask` operationId).
	DeleteTransferTaskWithResponse(ctx context.Context, scicatJobId string, params *DeleteTransferTaskParams, reqEditors ...RequestEditorFn) (*DeleteTransferTaskResponse, error)

	// GetVersionWithResponse get SciCat Globus Proxy version
	//
	// returns the current version of the proxy.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /version (the `GetVersion` operationId).
	GetVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetVersionResponse, error)
}

type PostTransferTaskResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// JobId the SciCat job id of the transfer job
		JobId string `json:"jobId"`
	}
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *GeneralErrorResponse
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *GeneralErrorResponse
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *GeneralErrorResponse
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *GeneralErrorResponse
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *GeneralErrorResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PostTransferTaskResponse) GetJSON200() *struct {
	// JobId the SciCat job id of the transfer job
	JobId string `json:"jobId"`
} {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r PostTransferTaskResponse) GetJSON400() *GeneralErrorResponse {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r PostTransferTaskResponse) GetJSON401() *GeneralErrorResponse {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r PostTransferTaskResponse) GetJSON403() *GeneralErrorResponse {
	return r.JSON403
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r PostTransferTaskResponse) GetJSON500() *GeneralErrorResponse {
	return r.JSON500
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r PostTransferTaskResponse) GetJSON503() *GeneralErrorResponse {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r PostTransferTaskResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostTransferTaskResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostTransferTaskResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostTransferTaskResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteTransferTaskResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *GeneralErrorResponse
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *GeneralErrorResponse
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *GeneralErrorResponse
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *GeneralErrorResponse
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r DeleteTransferTaskResponse) GetJSON400() *GeneralErrorResponse {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r DeleteTransferTaskResponse) GetJSON401() *GeneralErrorResponse {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r DeleteTransferTaskResponse) GetJSON403() *GeneralErrorResponse {
	return r.JSON403
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r DeleteTransferTaskResponse) GetJSON500() *GeneralErrorResponse {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r DeleteTransferTaskResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeleteTransferTaskResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteTransferTaskResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteTransferTaskResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetVersionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Version the current version of the service
		Version string `json:"version"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetVersionResponse) GetJSON200() *struct {
	// Version the current version of the service
	Version string `json:"version"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetVersionResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetVersionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetVersionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetVersionResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// PostTransferTaskWithBodyWithResponse request a transfer task
//
// It allows for requesting transfer tasks against a SciCat token. It uses the service account configured with the service's instance
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /transfer (the `PostTransferTask` operationId).
func (c *ClientWithResponses) PostTransferTaskWithBodyWithResponse(ctx context.Context, params *PostTransferTaskParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTransferTaskResponse, error) {
	rsp, err := c.PostTransferTaskWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTransferTaskResponse(rsp)
}

// PostTransferTaskWithResponse request a transfer task
//
// It allows for requesting transfer tasks against a SciCat token. It uses the service account configured with the service's instance
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /transfer (the `PostTransferTask` operationId).
func (c *ClientWithResponses) PostTransferTaskWithResponse(ctx context.Context, params *PostTransferTaskParams, body PostTransferTaskJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTransferTaskResponse, error) {
	rsp, err := c.PostTransferTask(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTransferTaskResponse(rsp)
}

// DeleteTransferTaskWithResponse cancels and/or deletes transfer entry
//
// allows the user to cancel a transfer and/or delete the job from the scicat job system.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /transfer/{scicatJobId} (the `DeleteTransferTask` operationId).
func (c *ClientWithResponses) DeleteTransferTaskWithResponse(ctx context.Context, scicatJobId string, params *DeleteTransferTaskParams, reqEditors ...RequestEditorFn) (*DeleteTransferTaskResponse, error) {
	rsp, err := c.DeleteTransferTask(ctx, scicatJobId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteTransferTaskResponse(rsp)
}

// GetVersionWithResponse get SciCat Globus Proxy version
//
// returns the current version of the proxy.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /version (the `GetVersion` operationId).
func (c *ClientWithResponses) GetVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetVersionResponse, error) {
	rsp, err := c.GetVersion(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetVersionResponse(rsp)
}

// ParsePostTransferTaskResponse parses an HTTP response from a PostTransferTaskWithResponse call
func ParsePostTransferTaskResponse(rsp *http.Response) (*PostTransferTaskResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostTransferTaskResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// JobId the SciCat job id of the transfer job
			JobId string `json:"jobId"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest GeneralErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest GeneralErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest GeneralErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest GeneralErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest GeneralErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseDeleteTransferTaskResponse parses an HTTP response from a DeleteTransferTaskWithResponse call
func ParseDeleteTransferTaskResponse(rsp *http.Response) (*DeleteTransferTaskResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteTransferTaskResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 200:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest GeneralErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest GeneralErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest GeneralErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest GeneralErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetVersionResponse parses an HTTP response from a GetVersionWithResponse call
func ParseGetVersionResponse(rsp *http.Response) (*GetVersionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetVersionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Version the current version of the service
			Version string `json:"version"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
