Scicat:
  Host: http://scicat.psi.ch/api/v3
  AccessToken: "token"
Transfer:
  Method: S3
  S3:
    Endpoint: s3.ethz.ch:9000
    Bucket: landingzone
    Checksum: true
  Globus:
    Endpoint: globus.psi.ch
Misc:
  ConcurrencyLimit: 2