// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AvailableExtractors() {
  return window['go']['main']['App']['AvailableExtractors']();
}

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function ExtractMetadata(arg1, arg2) {
  return window['go']['main']['App']['ExtractMetadata'](arg1, arg2);
}

export function RemoveTask(arg1) {
  return window['go']['main']['App']['RemoveTask'](arg1);
}

export function ScheduleTask(arg1) {
  return window['go']['main']['App']['ScheduleTask'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}
