// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {uuid} from '../models';

export function AvailableMethods():Promise<Array<main.ExtractionMethod>>;

export function CancelTask(arg1:uuid.UUID):Promise<void>;

export function ExtractMetadata(arg1:string,arg2:uuid.UUID):Promise<string>;

export function RemoveTask(arg1:uuid.UUID):Promise<void>;

export function ScheduleTask(arg1:uuid.UUID):Promise<void>;

export function SelectFolder():Promise<void>;
