// Package webserver provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package webserver

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

const (
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for TransferItemStatus.
const (
	Cancelled     TransferItemStatus = "cancelled"
	Failed        TransferItemStatus = "failed"
	Finished      TransferItemStatus = "finished"
	InvalidStatus TransferItemStatus = "invalid status"
	Transferring  TransferItemStatus = "transferring"
	Waiting       TransferItemStatus = "waiting"
)

// DeleteTransferRequest defines model for DeleteTransferRequest.
type DeleteTransferRequest struct {
	// TransferId id of the transfer that should be cancelled
	TransferId string `json:"transferId"`
}

// DeleteTransferResponse defines model for DeleteTransferResponse.
type DeleteTransferResponse struct {
	// Status New status of the transfer.
	Status *string `json:"status,omitempty"`

	// TransferId Transfer id affected
	TransferId string `json:"transferId"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// FolderNode a method item describes the method's name and schema
type FolderNode struct {
	Children        bool   `json:"children"`
	Name            string `json:"name"`
	Path            string `json:"path"`
	ProbablyDataset *bool  `json:"probablyDataset,omitempty"`
}

// GetBrowseDatasetResponse defines model for GetBrowseDatasetResponse.
type GetBrowseDatasetResponse struct {
	Folders *[]FolderNode `json:"folders,omitempty"`

	// Total Total number of folders.
	Total *int `json:"total,omitempty"`
}

// GetDatasetResponse defines model for GetDatasetResponse.
type GetDatasetResponse struct {
	Datasets []string `json:"datasets"`

	// Total Total number of datasets.
	Total int `json:"total"`
}

// GetExtractorResponse defines model for GetExtractorResponse.
type GetExtractorResponse struct {
	// Methods List of the metadata extraction method names configured in the ingestor
	Methods []MethodItem `json:"methods"`

	// Total Total number of methods
	Total int `json:"total"`
}

// GetTransferResponse defines model for GetTransferResponse.
type GetTransferResponse struct {
	// Total Total number of transfers.
	Total     *int            `json:"total,omitempty"`
	Transfers *[]TransferItem `json:"transfers,omitempty"`
}

// MethodItem a method item describes the method's name and schema
type MethodItem struct {
	Name   string `json:"name"`
	Schema string `json:"schema"`
}

// OtherHealthResponse defines model for OtherHealthResponse.
type OtherHealthResponse struct {
	Errors *map[string]string `json:"errors,omitempty"`

	// Status Status of the ingestor.
	Status string `json:"status"`
}

// OtherVersionResponse defines model for OtherVersionResponse.
type OtherVersionResponse struct {
	// Version Version of the ingestor.
	Version *string `json:"version,omitempty"`
}

// PostDatasetRequest defines model for PostDatasetRequest.
type PostDatasetRequest struct {
	// MetaData The metadata of the dataset.
	MetaData string `json:"metaData"`

	// UserToken the scicat token for acting on behalf of the user
	UserToken string `json:"userToken"`
}

// PostDatasetResponse defines model for PostDatasetResponse.
type PostDatasetResponse struct {
	// Status The status of the transfer. Can be used to send a message back to the ui.
	Status *string `json:"status,omitempty"`

	// TransferId The unique transfer id of the dataset transfer job.
	TransferId string `json:"transferId"`
}

// TransferItem defines model for TransferItem.
type TransferItem struct {
	BytesTotal       *int               `json:"bytesTotal,omitempty"`
	BytesTransferred *int               `json:"bytesTransferred,omitempty"`
	FilesTotal       *int               `json:"filesTotal,omitempty"`
	FilesTransferred *int               `json:"filesTransferred,omitempty"`
	Message          *string            `json:"message,omitempty"`
	Status           TransferItemStatus `json:"status"`
	TransferId       string             `json:"transferId"`
}

// TransferItemStatus defines model for TransferItem.Status.
type TransferItemStatus string

// UserInfo defines model for UserInfo.
type UserInfo struct {
	Email             *string    `json:"email,omitempty"`
	ExpiresAt         *time.Time `json:"expires_at,omitempty"`
	FamilyName        *string    `json:"family_name,omitempty"`
	GivenName         *string    `json:"given_name,omitempty"`
	LoggedIn          bool       `json:"logged_in"`
	Name              *string    `json:"name,omitempty"`
	PreferredUsername *string    `json:"preferred_username,omitempty"`
	Profile           *string    `json:"profile,omitempty"`
	Roles             *[]string  `json:"roles,omitempty"`
	Subject           *string    `json:"subject,omitempty"`
}

// GetCallbackParams defines parameters for GetCallback.
type GetCallbackParams struct {
	// Code For handling the authorization code received from the OIDC provider
	Code string `form:"code" json:"code"`

	// State parameter for CSRF protection
	State string `form:"state" json:"state"`
}

// DatasetControllerGetDatasetParams defines parameters for DatasetControllerGetDataset.
type DatasetControllerGetDatasetParams struct {
	Page     *uint `form:"page,omitempty" json:"page,omitempty"`
	PageSize *uint `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// FilesystemControllerBrowseFilesystemParams defines parameters for FilesystemControllerBrowseFilesystem.
type FilesystemControllerBrowseFilesystemParams struct {
	Path     string `form:"path" json:"path"`
	Page     *uint  `form:"page,omitempty" json:"page,omitempty"`
	PageSize *uint  `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// ExtractorControllerGetExtractorMethodsParams defines parameters for ExtractorControllerGetExtractorMethods.
type ExtractorControllerGetExtractorMethodsParams struct {
	Page     *uint `form:"page,omitempty" json:"page,omitempty"`
	PageSize *uint `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// GetGlobusCallbackParams defines parameters for GetGlobusCallback.
type GetGlobusCallbackParams struct {
	// Code For handling the authorization code received from Globus
	Code string `form:"code" json:"code"`

	// State parameter for CSRF protection
	State string `form:"state" json:"state"`
}

// ExtractMetadataParams defines parameters for ExtractMetadata.
type ExtractMetadataParams struct {
	FilePath   string `form:"filePath" json:"filePath"`
	MethodName string `form:"methodName" json:"methodName"`
}

// TransferControllerGetTransferParams defines parameters for TransferControllerGetTransfer.
type TransferControllerGetTransferParams struct {
	TransferId *string `form:"transferId,omitempty" json:"transferId,omitempty"`
	Page       *uint   `form:"page,omitempty" json:"page,omitempty"`
	PageSize   *uint   `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// DatasetControllerIngestDatasetJSONRequestBody defines body for DatasetControllerIngestDataset for application/json ContentType.
type DatasetControllerIngestDatasetJSONRequestBody = PostDatasetRequest

// TransferControllerDeleteTransferJSONRequestBody defines body for TransferControllerDeleteTransfer for application/json ContentType.
type TransferControllerDeleteTransferJSONRequestBody = DeleteTransferRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// OIDC callback
	// (GET /callback)
	GetCallback(c *gin.Context, params GetCallbackParams)
	// Get the available datasets.
	// (GET /dataset)
	DatasetControllerGetDataset(c *gin.Context, params DatasetControllerGetDatasetParams)
	// Ingest a new dataset
	// (POST /dataset)
	DatasetControllerIngestDataset(c *gin.Context)
	// Get a list of folders to a specific path.
	// (GET /dataset/browse)
	FilesystemControllerBrowseFilesystem(c *gin.Context, params FilesystemControllerBrowseFilesystemParams)
	// Get available extraction methods
	// (GET /extractor)
	ExtractorControllerGetExtractorMethods(c *gin.Context, params ExtractorControllerGetExtractorMethodsParams)
	// callback for globus
	// (GET /globus-callback)
	GetGlobusCallback(c *gin.Context, params GetGlobusCallbackParams)
	// Get the health status.
	// (GET /health)
	OtherControllerGetHealth(c *gin.Context)
	// OIDC login
	// (GET /login)
	GetLogin(c *gin.Context)
	// end user session
	// (GET /logout)
	GetLogout(c *gin.Context)
	// get metadata of a dataset
	// (GET /metadata)
	ExtractMetadata(c *gin.Context, params ExtractMetadataParams)
	// Cancel a data transfer
	// (DELETE /transfer)
	TransferControllerDeleteTransfer(c *gin.Context)
	// Get list of transfers. Optional use the transferId parameter to only get one item.
	// (GET /transfer)
	TransferControllerGetTransfer(c *gin.Context, params TransferControllerGetTransferParams)
	// returns user info to caller
	// (GET /userinfo)
	GetUserinfo(c *gin.Context)
	// Get the used ingestor version
	// (GET /version)
	OtherControllerGetVersion(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetCallback operation middleware
func (siw *ServerInterfaceWrapper) GetCallback(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCallbackParams

	// ------------- Required query parameter "code" -------------

	if paramValue := c.Query("code"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument code is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "code", c.Request.URL.Query(), &params.Code)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter code: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "state" -------------

	if paramValue := c.Query("state"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument state is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "state", c.Request.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter state: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCallback(c, params)
}

// DatasetControllerGetDataset operation middleware
func (siw *ServerInterfaceWrapper) DatasetControllerGetDataset(c *gin.Context) {

	var err error

	c.Set(CookieAuthScopes, []string{"ingestor_read"})

	// Parameter object where we will unmarshal all parameters from the context
	var params DatasetControllerGetDatasetParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DatasetControllerGetDataset(c, params)
}

// DatasetControllerIngestDataset operation middleware
func (siw *ServerInterfaceWrapper) DatasetControllerIngestDataset(c *gin.Context) {

	c.Set(CookieAuthScopes, []string{"ingestor_write"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DatasetControllerIngestDataset(c)
}

// FilesystemControllerBrowseFilesystem operation middleware
func (siw *ServerInterfaceWrapper) FilesystemControllerBrowseFilesystem(c *gin.Context) {

	var err error

	c.Set(CookieAuthScopes, []string{"ingestor_read"})

	// Parameter object where we will unmarshal all parameters from the context
	var params FilesystemControllerBrowseFilesystemParams

	// ------------- Required query parameter "path" -------------

	if paramValue := c.Query("path"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument path is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "path", c.Request.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter path: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.FilesystemControllerBrowseFilesystem(c, params)
}

// ExtractorControllerGetExtractorMethods operation middleware
func (siw *ServerInterfaceWrapper) ExtractorControllerGetExtractorMethods(c *gin.Context) {

	var err error

	c.Set(CookieAuthScopes, []string{"ingestor_read"})

	// Parameter object where we will unmarshal all parameters from the context
	var params ExtractorControllerGetExtractorMethodsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExtractorControllerGetExtractorMethods(c, params)
}

// GetGlobusCallback operation middleware
func (siw *ServerInterfaceWrapper) GetGlobusCallback(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetGlobusCallbackParams

	// ------------- Required query parameter "code" -------------

	if paramValue := c.Query("code"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument code is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "code", c.Request.URL.Query(), &params.Code)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter code: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "state" -------------

	if paramValue := c.Query("state"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument state is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "state", c.Request.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter state: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGlobusCallback(c, params)
}

// OtherControllerGetHealth operation middleware
func (siw *ServerInterfaceWrapper) OtherControllerGetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.OtherControllerGetHealth(c)
}

// GetLogin operation middleware
func (siw *ServerInterfaceWrapper) GetLogin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLogin(c)
}

// GetLogout operation middleware
func (siw *ServerInterfaceWrapper) GetLogout(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLogout(c)
}

// ExtractMetadata operation middleware
func (siw *ServerInterfaceWrapper) ExtractMetadata(c *gin.Context) {

	var err error

	c.Set(CookieAuthScopes, []string{"ingestor_read"})

	// Parameter object where we will unmarshal all parameters from the context
	var params ExtractMetadataParams

	// ------------- Required query parameter "filePath" -------------

	if paramValue := c.Query("filePath"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument filePath is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "filePath", c.Request.URL.Query(), &params.FilePath)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter filePath: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "methodName" -------------

	if paramValue := c.Query("methodName"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument methodName is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "methodName", c.Request.URL.Query(), &params.MethodName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter methodName: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExtractMetadata(c, params)
}

// TransferControllerDeleteTransfer operation middleware
func (siw *ServerInterfaceWrapper) TransferControllerDeleteTransfer(c *gin.Context) {

	c.Set(CookieAuthScopes, []string{"ingestor_write"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.TransferControllerDeleteTransfer(c)
}

// TransferControllerGetTransfer operation middleware
func (siw *ServerInterfaceWrapper) TransferControllerGetTransfer(c *gin.Context) {

	var err error

	c.Set(CookieAuthScopes, []string{"ingestor_read"})

	// Parameter object where we will unmarshal all parameters from the context
	var params TransferControllerGetTransferParams

	// ------------- Optional query parameter "transferId" -------------

	err = runtime.BindQueryParameter("form", true, false, "transferId", c.Request.URL.Query(), &params.TransferId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter transferId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.TransferControllerGetTransfer(c, params)
}

// GetUserinfo operation middleware
func (siw *ServerInterfaceWrapper) GetUserinfo(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUserinfo(c)
}

// OtherControllerGetVersion operation middleware
func (siw *ServerInterfaceWrapper) OtherControllerGetVersion(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.OtherControllerGetVersion(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/callback", wrapper.GetCallback)
	router.GET(options.BaseURL+"/dataset", wrapper.DatasetControllerGetDataset)
	router.POST(options.BaseURL+"/dataset", wrapper.DatasetControllerIngestDataset)
	router.GET(options.BaseURL+"/dataset/browse", wrapper.FilesystemControllerBrowseFilesystem)
	router.GET(options.BaseURL+"/extractor", wrapper.ExtractorControllerGetExtractorMethods)
	router.GET(options.BaseURL+"/globus-callback", wrapper.GetGlobusCallback)
	router.GET(options.BaseURL+"/health", wrapper.OtherControllerGetHealth)
	router.GET(options.BaseURL+"/login", wrapper.GetLogin)
	router.GET(options.BaseURL+"/logout", wrapper.GetLogout)
	router.GET(options.BaseURL+"/metadata", wrapper.ExtractMetadata)
	router.DELETE(options.BaseURL+"/transfer", wrapper.TransferControllerDeleteTransfer)
	router.GET(options.BaseURL+"/transfer", wrapper.TransferControllerGetTransfer)
	router.GET(options.BaseURL+"/userinfo", wrapper.GetUserinfo)
	router.GET(options.BaseURL+"/version", wrapper.OtherControllerGetVersion)
}

type GetCallbackRequestObject struct {
	Params GetCallbackParams
}

type GetCallbackResponseObject interface {
	VisitGetCallbackResponse(w http.ResponseWriter) error
}

type GetCallback302ResponseHeaders struct {
	Location string
}

type GetCallback302Response struct {
	Headers GetCallback302ResponseHeaders
}

func (response GetCallback302Response) VisitGetCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(302)
	return nil
}

type GetCallback400TextResponse string

func (response GetCallback400TextResponse) VisitGetCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(400)

	_, err := w.Write([]byte(response))
	return err
}

type GetCallback500TextResponse string

func (response GetCallback500TextResponse) VisitGetCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(500)

	_, err := w.Write([]byte(response))
	return err
}

type DatasetControllerGetDatasetRequestObject struct {
	Params DatasetControllerGetDatasetParams
}

type DatasetControllerGetDatasetResponseObject interface {
	VisitDatasetControllerGetDatasetResponse(w http.ResponseWriter) error
}

type DatasetControllerGetDataset200JSONResponse GetDatasetResponse

func (response DatasetControllerGetDataset200JSONResponse) VisitDatasetControllerGetDatasetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DatasetControllerGetDataset400TextResponse string

func (response DatasetControllerGetDataset400TextResponse) VisitDatasetControllerGetDatasetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(400)

	_, err := w.Write([]byte(response))
	return err
}

type DatasetControllerIngestDatasetRequestObject struct {
	Body *DatasetControllerIngestDatasetJSONRequestBody
}

type DatasetControllerIngestDatasetResponseObject interface {
	VisitDatasetControllerIngestDatasetResponse(w http.ResponseWriter) error
}

type DatasetControllerIngestDataset200JSONResponse PostDatasetResponse

func (response DatasetControllerIngestDataset200JSONResponse) VisitDatasetControllerIngestDatasetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DatasetControllerIngestDataset400TextResponse string

func (response DatasetControllerIngestDataset400TextResponse) VisitDatasetControllerIngestDatasetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(400)

	_, err := w.Write([]byte(response))
	return err
}

type FilesystemControllerBrowseFilesystemRequestObject struct {
	Params FilesystemControllerBrowseFilesystemParams
}

type FilesystemControllerBrowseFilesystemResponseObject interface {
	VisitFilesystemControllerBrowseFilesystemResponse(w http.ResponseWriter) error
}

type FilesystemControllerBrowseFilesystem200JSONResponse GetBrowseDatasetResponse

func (response FilesystemControllerBrowseFilesystem200JSONResponse) VisitFilesystemControllerBrowseFilesystemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type FilesystemControllerBrowseFilesystem400TextResponse string

func (response FilesystemControllerBrowseFilesystem400TextResponse) VisitFilesystemControllerBrowseFilesystemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(400)

	_, err := w.Write([]byte(response))
	return err
}

type ExtractorControllerGetExtractorMethodsRequestObject struct {
	Params ExtractorControllerGetExtractorMethodsParams
}

type ExtractorControllerGetExtractorMethodsResponseObject interface {
	VisitExtractorControllerGetExtractorMethodsResponse(w http.ResponseWriter) error
}

type ExtractorControllerGetExtractorMethods200JSONResponse GetExtractorResponse

func (response ExtractorControllerGetExtractorMethods200JSONResponse) VisitExtractorControllerGetExtractorMethodsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetGlobusCallbackRequestObject struct {
	Params GetGlobusCallbackParams
}

type GetGlobusCallbackResponseObject interface {
	VisitGetGlobusCallbackResponse(w http.ResponseWriter) error
}

type GetGlobusCallback302ResponseHeaders struct {
	Location string
}

type GetGlobusCallback302Response struct {
	Headers GetGlobusCallback302ResponseHeaders
}

func (response GetGlobusCallback302Response) VisitGetGlobusCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(302)
	return nil
}

type GetGlobusCallback400TextResponse string

func (response GetGlobusCallback400TextResponse) VisitGetGlobusCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(400)

	_, err := w.Write([]byte(response))
	return err
}

type GetGlobusCallback500TextResponse string

func (response GetGlobusCallback500TextResponse) VisitGetGlobusCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(500)

	_, err := w.Write([]byte(response))
	return err
}

type OtherControllerGetHealthRequestObject struct {
}

type OtherControllerGetHealthResponseObject interface {
	VisitOtherControllerGetHealthResponse(w http.ResponseWriter) error
}

type OtherControllerGetHealth200JSONResponse OtherHealthResponse

func (response OtherControllerGetHealth200JSONResponse) VisitOtherControllerGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type OtherControllerGetHealth400TextResponse string

func (response OtherControllerGetHealth400TextResponse) VisitOtherControllerGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(400)

	_, err := w.Write([]byte(response))
	return err
}

type GetLoginRequestObject struct {
}

type GetLoginResponseObject interface {
	VisitGetLoginResponse(w http.ResponseWriter) error
}

type GetLogin302ResponseHeaders struct {
	Location string
}

type GetLogin302Response struct {
	Headers GetLogin302ResponseHeaders
}

func (response GetLogin302Response) VisitGetLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(302)
	return nil
}

type GetLogoutRequestObject struct {
}

type GetLogoutResponseObject interface {
	VisitGetLogoutResponse(w http.ResponseWriter) error
}

type GetLogout302ResponseHeaders struct {
	Location string
}

type GetLogout302Response struct {
	Headers GetLogout302ResponseHeaders
}

func (response GetLogout302Response) VisitGetLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(302)
	return nil
}

type GetLogout500TextResponse string

func (response GetLogout500TextResponse) VisitGetLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(500)

	_, err := w.Write([]byte(response))
	return err
}

type ExtractMetadataRequestObject struct {
	Params ExtractMetadataParams
}

type ExtractMetadataResponseObject interface {
	VisitExtractMetadataResponse(w http.ResponseWriter) error
}

type ExtractMetadata200ResponseHeaders struct {
	CacheControl string
	Connection   string
	ContentType  string
}

type ExtractMetadata200TexteventStreamResponse struct {
	Body          io.Reader
	Headers       ExtractMetadata200ResponseHeaders
	ContentLength int64
}

func (response ExtractMetadata200TexteventStreamResponse) VisitExtractMetadataResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.Header().Set("Cache-Control", fmt.Sprint(response.Headers.CacheControl))
	w.Header().Set("Connection", fmt.Sprint(response.Headers.Connection))
	w.Header().Set("Content-Type", fmt.Sprint(response.Headers.ContentType))
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type ExtractMetadatadefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ExtractMetadatadefaultJSONResponse) VisitExtractMetadataResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type TransferControllerDeleteTransferRequestObject struct {
	Body *TransferControllerDeleteTransferJSONRequestBody
}

type TransferControllerDeleteTransferResponseObject interface {
	VisitTransferControllerDeleteTransferResponse(w http.ResponseWriter) error
}

type TransferControllerDeleteTransfer200JSONResponse DeleteTransferResponse

func (response TransferControllerDeleteTransfer200JSONResponse) VisitTransferControllerDeleteTransferResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type TransferControllerDeleteTransfer400TextResponse string

func (response TransferControllerDeleteTransfer400TextResponse) VisitTransferControllerDeleteTransferResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(400)

	_, err := w.Write([]byte(response))
	return err
}

type TransferControllerGetTransferRequestObject struct {
	Params TransferControllerGetTransferParams
}

type TransferControllerGetTransferResponseObject interface {
	VisitTransferControllerGetTransferResponse(w http.ResponseWriter) error
}

type TransferControllerGetTransfer200JSONResponse GetTransferResponse

func (response TransferControllerGetTransfer200JSONResponse) VisitTransferControllerGetTransferResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type TransferControllerGetTransfer400TextResponse string

func (response TransferControllerGetTransfer400TextResponse) VisitTransferControllerGetTransferResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(400)

	_, err := w.Write([]byte(response))
	return err
}

type GetUserinfoRequestObject struct {
}

type GetUserinfoResponseObject interface {
	VisitGetUserinfoResponse(w http.ResponseWriter) error
}

type GetUserinfo200JSONResponse UserInfo

func (response GetUserinfo200JSONResponse) VisitGetUserinfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUserinfo400TextResponse string

func (response GetUserinfo400TextResponse) VisitGetUserinfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(400)

	_, err := w.Write([]byte(response))
	return err
}

type GetUserinfo500TextResponse string

func (response GetUserinfo500TextResponse) VisitGetUserinfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(500)

	_, err := w.Write([]byte(response))
	return err
}

type OtherControllerGetVersionRequestObject struct {
}

type OtherControllerGetVersionResponseObject interface {
	VisitOtherControllerGetVersionResponse(w http.ResponseWriter) error
}

type OtherControllerGetVersion200JSONResponse OtherVersionResponse

func (response OtherControllerGetVersion200JSONResponse) VisitOtherControllerGetVersionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type OtherControllerGetVersion400TextResponse string

func (response OtherControllerGetVersion400TextResponse) VisitOtherControllerGetVersionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(400)

	_, err := w.Write([]byte(response))
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// OIDC callback
	// (GET /callback)
	GetCallback(ctx context.Context, request GetCallbackRequestObject) (GetCallbackResponseObject, error)
	// Get the available datasets.
	// (GET /dataset)
	DatasetControllerGetDataset(ctx context.Context, request DatasetControllerGetDatasetRequestObject) (DatasetControllerGetDatasetResponseObject, error)
	// Ingest a new dataset
	// (POST /dataset)
	DatasetControllerIngestDataset(ctx context.Context, request DatasetControllerIngestDatasetRequestObject) (DatasetControllerIngestDatasetResponseObject, error)
	// Get a list of folders to a specific path.
	// (GET /dataset/browse)
	FilesystemControllerBrowseFilesystem(ctx context.Context, request FilesystemControllerBrowseFilesystemRequestObject) (FilesystemControllerBrowseFilesystemResponseObject, error)
	// Get available extraction methods
	// (GET /extractor)
	ExtractorControllerGetExtractorMethods(ctx context.Context, request ExtractorControllerGetExtractorMethodsRequestObject) (ExtractorControllerGetExtractorMethodsResponseObject, error)
	// callback for globus
	// (GET /globus-callback)
	GetGlobusCallback(ctx context.Context, request GetGlobusCallbackRequestObject) (GetGlobusCallbackResponseObject, error)
	// Get the health status.
	// (GET /health)
	OtherControllerGetHealth(ctx context.Context, request OtherControllerGetHealthRequestObject) (OtherControllerGetHealthResponseObject, error)
	// OIDC login
	// (GET /login)
	GetLogin(ctx context.Context, request GetLoginRequestObject) (GetLoginResponseObject, error)
	// end user session
	// (GET /logout)
	GetLogout(ctx context.Context, request GetLogoutRequestObject) (GetLogoutResponseObject, error)
	// get metadata of a dataset
	// (GET /metadata)
	ExtractMetadata(ctx context.Context, request ExtractMetadataRequestObject) (ExtractMetadataResponseObject, error)
	// Cancel a data transfer
	// (DELETE /transfer)
	TransferControllerDeleteTransfer(ctx context.Context, request TransferControllerDeleteTransferRequestObject) (TransferControllerDeleteTransferResponseObject, error)
	// Get list of transfers. Optional use the transferId parameter to only get one item.
	// (GET /transfer)
	TransferControllerGetTransfer(ctx context.Context, request TransferControllerGetTransferRequestObject) (TransferControllerGetTransferResponseObject, error)
	// returns user info to caller
	// (GET /userinfo)
	GetUserinfo(ctx context.Context, request GetUserinfoRequestObject) (GetUserinfoResponseObject, error)
	// Get the used ingestor version
	// (GET /version)
	OtherControllerGetVersion(ctx context.Context, request OtherControllerGetVersionRequestObject) (OtherControllerGetVersionResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetCallback operation middleware
func (sh *strictHandler) GetCallback(ctx *gin.Context, params GetCallbackParams) {
	var request GetCallbackRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCallback(ctx, request.(GetCallbackRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCallback")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetCallbackResponseObject); ok {
		if err := validResponse.VisitGetCallbackResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DatasetControllerGetDataset operation middleware
func (sh *strictHandler) DatasetControllerGetDataset(ctx *gin.Context, params DatasetControllerGetDatasetParams) {
	var request DatasetControllerGetDatasetRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DatasetControllerGetDataset(ctx, request.(DatasetControllerGetDatasetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DatasetControllerGetDataset")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DatasetControllerGetDatasetResponseObject); ok {
		if err := validResponse.VisitDatasetControllerGetDatasetResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DatasetControllerIngestDataset operation middleware
func (sh *strictHandler) DatasetControllerIngestDataset(ctx *gin.Context) {
	var request DatasetControllerIngestDatasetRequestObject

	var body DatasetControllerIngestDatasetJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DatasetControllerIngestDataset(ctx, request.(DatasetControllerIngestDatasetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DatasetControllerIngestDataset")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DatasetControllerIngestDatasetResponseObject); ok {
		if err := validResponse.VisitDatasetControllerIngestDatasetResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// FilesystemControllerBrowseFilesystem operation middleware
func (sh *strictHandler) FilesystemControllerBrowseFilesystem(ctx *gin.Context, params FilesystemControllerBrowseFilesystemParams) {
	var request FilesystemControllerBrowseFilesystemRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.FilesystemControllerBrowseFilesystem(ctx, request.(FilesystemControllerBrowseFilesystemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "FilesystemControllerBrowseFilesystem")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(FilesystemControllerBrowseFilesystemResponseObject); ok {
		if err := validResponse.VisitFilesystemControllerBrowseFilesystemResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExtractorControllerGetExtractorMethods operation middleware
func (sh *strictHandler) ExtractorControllerGetExtractorMethods(ctx *gin.Context, params ExtractorControllerGetExtractorMethodsParams) {
	var request ExtractorControllerGetExtractorMethodsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ExtractorControllerGetExtractorMethods(ctx, request.(ExtractorControllerGetExtractorMethodsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExtractorControllerGetExtractorMethods")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ExtractorControllerGetExtractorMethodsResponseObject); ok {
		if err := validResponse.VisitExtractorControllerGetExtractorMethodsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetGlobusCallback operation middleware
func (sh *strictHandler) GetGlobusCallback(ctx *gin.Context, params GetGlobusCallbackParams) {
	var request GetGlobusCallbackRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetGlobusCallback(ctx, request.(GetGlobusCallbackRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGlobusCallback")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetGlobusCallbackResponseObject); ok {
		if err := validResponse.VisitGetGlobusCallbackResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// OtherControllerGetHealth operation middleware
func (sh *strictHandler) OtherControllerGetHealth(ctx *gin.Context) {
	var request OtherControllerGetHealthRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.OtherControllerGetHealth(ctx, request.(OtherControllerGetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "OtherControllerGetHealth")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(OtherControllerGetHealthResponseObject); ok {
		if err := validResponse.VisitOtherControllerGetHealthResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLogin operation middleware
func (sh *strictHandler) GetLogin(ctx *gin.Context) {
	var request GetLoginRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetLogin(ctx, request.(GetLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLogin")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetLoginResponseObject); ok {
		if err := validResponse.VisitGetLoginResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLogout operation middleware
func (sh *strictHandler) GetLogout(ctx *gin.Context) {
	var request GetLogoutRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetLogout(ctx, request.(GetLogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLogout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetLogoutResponseObject); ok {
		if err := validResponse.VisitGetLogoutResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExtractMetadata operation middleware
func (sh *strictHandler) ExtractMetadata(ctx *gin.Context, params ExtractMetadataParams) {
	var request ExtractMetadataRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ExtractMetadata(ctx, request.(ExtractMetadataRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExtractMetadata")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ExtractMetadataResponseObject); ok {
		if err := validResponse.VisitExtractMetadataResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// TransferControllerDeleteTransfer operation middleware
func (sh *strictHandler) TransferControllerDeleteTransfer(ctx *gin.Context) {
	var request TransferControllerDeleteTransferRequestObject

	var body TransferControllerDeleteTransferJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.TransferControllerDeleteTransfer(ctx, request.(TransferControllerDeleteTransferRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TransferControllerDeleteTransfer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(TransferControllerDeleteTransferResponseObject); ok {
		if err := validResponse.VisitTransferControllerDeleteTransferResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// TransferControllerGetTransfer operation middleware
func (sh *strictHandler) TransferControllerGetTransfer(ctx *gin.Context, params TransferControllerGetTransferParams) {
	var request TransferControllerGetTransferRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.TransferControllerGetTransfer(ctx, request.(TransferControllerGetTransferRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TransferControllerGetTransfer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(TransferControllerGetTransferResponseObject); ok {
		if err := validResponse.VisitTransferControllerGetTransferResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUserinfo operation middleware
func (sh *strictHandler) GetUserinfo(ctx *gin.Context) {
	var request GetUserinfoRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUserinfo(ctx, request.(GetUserinfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUserinfo")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetUserinfoResponseObject); ok {
		if err := validResponse.VisitGetUserinfoResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// OtherControllerGetVersion operation middleware
func (sh *strictHandler) OtherControllerGetVersion(ctx *gin.Context) {
	var request OtherControllerGetVersionRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.OtherControllerGetVersion(ctx, request.(OtherControllerGetVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "OtherControllerGetVersion")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(OtherControllerGetVersionResponseObject); ok {
		if err := validResponse.VisitOtherControllerGetVersionResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbW28bN/b/Kgfz/wNJAFn2tt198FvqOql2c0OcLLCIjZSaOZLYcMgJybGiFv7ui8PL",
	"XKnbxu622D4YsDQcnvvvXEj9muWqrJREaU12/mtm8hWWzP37Awq0+E4zaRao3+LnGo2lB5VWFWrL0S2z",
	"YcGsoE8FmlzzynIls/OMF6AWYFcIcRXYFbNgVqoWBcwRciZzFAKLbJLZTYXZeWas5nKZ3d1NMo2fa66x",
	"yM4/dOncNGvV/GfMbXY3GXFrKiUNjtk1ltnajFl9hWvwz4YsT8esTXZKHZkAXgBbLDC3Xy/epdZKj6XJ",
	"VeFkHPFXojFsmXo2oOt2aNenaD9TokD9KpDqy8qgRLtSBXCLJfhnczROgf7JIwOSlQhMFuC9K5sMpVhx",
	"UWiUHW7nSglkksjT20kZK2ZX6QdazdlcbH5glhm0qW0HWnA0wo6Tlp+UNp6j/V6rtcGw+3ZXWzi9uX9J",
	"O+6f/9e4yM6z/zttw+40xNxpR893DWGmNdu4z8oykXA2+hpkXc5Rk+cGoh2n5dLiErWTOSXNXjkKv6Av",
	"yDgi/jN+4+ZbGO4aqeEjbr7FPJdfrGa5VTtQwLtmAgZecGMjAJRoGdEE9BtyJaO3k78YyJVc8GWtsQAu",
	"3StcLtFYpbPJYSZ/6babWSy/QoVRmL0K7Czcpb/9IHogYxHTksZtMfTwCImcpRWW8u+Ogh8Gu7aiU1i/",
	"F4AD9ITlKZO8tivUPyITdrXdJEgJwv3HioKThEy86RttS8S2hLblxqteXow+Pt2b08J+JBzPmb2KH5dC",
	"zWsTPm6V+J+oDVdyu8i3fsGY3/DmYQyPiL9RpsXELUUPQQOtScRAFzgCAwG4koVEbVC/U58wIQa96jUH",
	"llbAQmkgHJJLUBLmuGJiEWnQPnsN0rDdpXuzTwfHllKkgi2lFFwwYpy4LcAqMCgLoDh01QfMWf6JvnYC",
	"8eMLL3pN8s91p95sS9BghfbRz2o+/dq6rIdIIw3NNxbNuwiWYwT0z8MWjmBq1YKLnbv45/t22V4RdgMf",
	"ZV2S2GvGyc+yVuHaf1xwyc3KFbQLxn3h3i3iubxlghfBATo622bCg9XfsJmyw3uDeiYXKgGMJeMiKTV+",
	"qbhG85FZX63pkv6jMgNPLHeoPHpnwUouNh+3ov6S36Lc/lio5RKLj/zoUlejt+1HitsdyxQ5Q/KZVgKP",
	"LOFM7fW710qtWGPb0D6Y15rbzRXluNi4qE8cn9a+gid9hK+yqIWsj2is4v9ASvJ35GPe0P3of4vGwtM3",
	"MweTuSrLWhJ2cgeVdo3oS7RZyAbwfubyevOZwIfgyKC+5TlOgeBk8GVnXzSw5nbl9rx8eXKV8wvqbOPL",
	"15JeJ3aYEGpt+l1wKHwnwGqrSmZ5nqw2Xd3hkTRC5OcaNUdfUXFLts4C6UaQp29m2aTNjtlfpmfTM7Kn",
	"qlCyimfn2bfTs+m3oeFx9jjNmRAkLH1Y+p6JosjpjwKVCsOLuIZe1KxE64q3D0NLPFMaVkwWgjIVyc1q",
	"u1Ka/+KtQS0naMyR32IBC61Kt+j17IcLqLS65YUzvHMKEnfT+kToVlvfs7rGnbXWkLeGcecmF1dvnxFN",
	"i07hW6iSCY4je0OLfd506v327JuxwzqBo97B1HmOxixqkU2yFbLYOgrlnXj8vsaCa8wtvH/7ItvFDcXM",
	"d2dnPu6kRelDGr/Y00owD0Y73p7s5NtnASgo6SqI8O9srDR41d1Nsr/eH/2ZtISBAq5Q36IGPxvpAk12",
	"/uGG4Kssmd4MOabIYUvy24z8EqUNMJHd0B6nRTs1CIEwxBmrOd6ic1rfboOxus5trTEWG+yWccHmAnsN",
	"bj+iQoF1oaTVSgjUbTM+jrCUX1aUz7uG7zP6hvAidGPk7BVbcunIEy9Nvqu5tMnecTvRK/7LLsKvxh0g",
	"VOgYwINID8Pnm5HzsKoSwWynPxs1cKFdPWRi4pHwsbCkE5ViAzpYvphm9xtRsxA1OvQbA1/up8sPWWxo",
	"PmpkRXZz1/P151TibvXA6PnRyW+oalAm4eYXGplFYE3djAJLlBa4hJBxXHqi7BjLa0IA/+wAb/f5qnX4",
	"IPz3qtjcm7ETvdxdv3ghJL97QHdLdVI7/M2blrJkJx/8PpxtrbnFobd5IwIDievoKUk36yDr6dzNT78O",
	"YF2hDVS/jF3tGTVEG2OxbL3Nz2zbJ4cirBsIb0/8Q8S1q8hgYHyjalgzSS08eLmTPeefAH+fAJ8e0Cdi",
	"IY57w9T8Dwr3DMRADquAgakw5wueN1GSjkqM4/LDArLNK6Ox+K6J+DhKmzF9rwBqvn3ZDKv/rIQeLFDG",
	"RyUJd306tLjSpg0OipkYMl/vyTucq+PArct6F/YD5ZNDetjnbunDdbJ+//+F9tVL+kdsYIec/xFa2JZZ",
	"pWEZnWxnI7tyR0b7UZ1LD0Nu4jRXte8f2gm+qlBeltAiyBjL3YFND8f9eVX2gPCVOhZLqNqviOL0YKuD",
	"W79lfk+2a6sum91krUjMYFGhlp6ZpEFnklvuBpPNOK0PVwuh1mPbPUf7wu17SNC/jSFrVX9g5w+nbN11",
	"wyNhYA8E7JvviCDEzpgQaqlquytBvPArDlGGX+o9CQssJtAgWjzJWqkSIVQnx2FiaD12g+JDQJLxkIR7",
	"IYk6/9pQc4bGeHvv1H2ccG914CvLtDXuPHA8C7fMfALVLyrB8AInfg4v+C1CXRUuAFoYq7RaajQGakM5",
	"PODtFS8QLm8JT+Dx1dXlk+m1nFlYcyEgF8r4UjdXUvrM2o76F5x0FKfxpHjGZawOGr4JyabXclvN+zJq",
	"4qDidsEFvjmuEX3nOBXovCh2pAaFu4vmRzUac6WLI5pRX4a98tcVjmGkodvu4NBiYOEUK/vLX+fvSJY8",
	"MVYjc6ew+IWVlTsbcU/Oo72uJdE8h3+pWiedLCA2cBP7l8811uhNeUQwPXWewWWtagOeL7KCD60Tg9KC",
	"48xM4ZLlK/8huJ93KbBrFUdu5hyYhJ/cop/AsqWbvDH4idh3X0z9cVN3Sf8+C3FMHHhC7hLmmhlwnMw3",
	"wT2IOX/s5Xf2G/W5oho4tzUTznzXMvhWtJJ/3amVW4Ni4V+fIzCxZhsDKKmucu3hnBn823cTJwy3BnwV",
	"AgVWKAsTY53+AtebiizxI2p8ZDpNb6WM4a5naJYZt6mPYe15KyhIHWOejjm/lnACQwcBAO8jDLx529tg",
	"PuRTKpvZRwZK5dixKP31hsExpFxGZA2lyGOpLDiCGgWz/kKEkzZ2N0GFT7qMOlhOsels2je6W+s0XhO4",
	"Y0HW4SboiQmjQJIuhNhAiUwav4mv/pzPRuM5TCyAGUcZgHdJMVgwy4QnN+0yG8G3xy9hoycUnMrEeZlQ",
	"a5JkwVEU5hyuM2OLj6q219kkfECt/QeNphb2OoPHqvKXnZ7Q1+5557vALpxA2CocqbqdgGkcKBy/YF5b",
	"akAfUdwyWTBdQPte+MIr1uvION+nNHGLYjNtKXoW3YuRGCvI9dercBTd0g23KsyEHmqM74Z70t3g66UY",
	"FzuRIjgyg1eY3HSt4wrgWkssogu3PDzmztE1OmRgcvNkCjP3FaXDtQp2IUFaklzmonalj/VSMdu4UkLA",
	"IsQlN41r0TrBTADEJlc53Xrc7dRNFyxf4UloNBLjFgU5y1fkRNz4g/cQiI5k2DTbfTnvosn6YwJPi1tu",
	"QnTlgqOf635CrIYFAzVNB1CiNHbyzj1Jpc6Xs5eXDXZ3ZCDxRplvurdcLHDBamHvrQWLbeso/72X+KXy",
	"ST9ZRx41GFqi7V2pa46k3K6ncbLmNSjQ4riuj7ej2ha1/3uBBzp+Sv+E4jc+gdryy4iE1ZofLvgLXf/V",
	"Jvm4Y6gLx3DwjGbW2mlImq9u7iZ7xiEsjoexaEqMdnrrGoGYX6jGtkgSjtvqsct1rlYfVvj3L7/tGhL+",
	"ORO/v5n4IZHyHC000fI7Gi0dPXAfOfgUXkfnrkMb3LohtONnq0BJsQECZyXR3aGfpgOOQLo2FCb+2t62",
	"ycv7uOYB7dvcE03o1s0yuAF/mxG4DG3W369ev6Lvm9KpGQY0Ut2vkV2ByGq7IqoFN1SPFlTrhcLzu7Mz",
	"emJ8z2hX7Q3qex5T86NnQl5Hxs+FSDXkKDkj+Ns3Hupc599/CpnXWpP4t9uv+u+bUIdfCTz4iHr4O4Zk",
	"VId5VhTndzumdp0tH7CbmlYfg0uTYXafZKwoufSAFbYe3Z6M5jXd/rnzG7GQkZpacXL4Di0cjpPxwRsl",
	"5kvtbu0J5ni7Z7UmLYJqt3WHPihRM9E9rmn383q/u7n7dwAAAP//khMm79E7AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
