// Package s3upload provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package s3upload

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
	SciCatAuthScopes = "SciCatAuth.Scopes"
)

// AbortUploadBody defines model for AbortUploadBody.
type AbortUploadBody struct {
	ObjectName string `json:"ObjectName"`
	UploadID   string `json:"UploadID"`
}

// AbortUploadResp defines model for AbortUploadResp.
type AbortUploadResp struct {
	Message    string `json:"Message"`
	ObjectName string `json:"ObjectName"`
	UploadID   string `json:"UploadID"`
}

// CompletePart defines model for CompletePart.
type CompletePart struct {
	ChecksumSHA256 string `json:"ChecksumSHA256"`
	ETag           string `json:"ETag"`
	PartNumber     int    `json:"PartNumber"`
}

// CompleteUploadBody defines model for CompleteUploadBody.
type CompleteUploadBody struct {
	ChecksumSHA256 string         `json:"ChecksumSHA256"`
	ObjectName     string         `json:"ObjectName"`
	Parts          []CompletePart `json:"Parts"`
	UploadID       string         `json:"UploadID"`
}

// CompleteUploadResp defines model for CompleteUploadResp.
type CompleteUploadResp struct {
	Key      string `json:"Key"`
	Location string `json:"Location"`
}

// CreateServiceTokenResp defines model for CreateServiceTokenResp.
type CreateServiceTokenResp struct {
	// AccessToken The JWT access token
	AccessToken string `json:"access_token"`

	// ExpiresIn The duration in seconds the access token is valid for
	ExpiresIn *int `json:"expires_in,omitempty"`

	// NotBeforePolicy Timestamp that indicates the time before which the JWT must not be accepted for processing
	NotBeforePolicy *int `json:"not-before-policy,omitempty"`

	// RefreshExpiresIn The duration in seconds the refresh token is valid for
	RefreshExpiresIn *int `json:"refresh_expires_in,omitempty"`

	// RefreshToken The JWT refresh token
	RefreshToken string `json:"refresh_token"`

	// Scope Claim in a JWT defines the set of permissions or access rights granted
	Scope *string `json:"scope,omitempty"`

	// SessionState Session ID, identifier that uniquely ties the session to the authenticated user
	SessionState *string `json:"session_state,omitempty"`

	// TokenType Bearer
	TokenType *string `json:"token_type,omitempty"`
}

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	Detail *[]ValidationError `json:"detail,omitempty"`
}

// InternalError defines model for InternalError.
type InternalError struct {
	// Code A specific error code indicating the error type
	Code string `json:"code"`

	// Details Additional context or information about the error
	Details *string `json:"details,omitempty"`

	// Message A human-readable message providing more details about the error
	Message string `json:"message"`

	// Timestamp The time when the error occurred
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// PresignedUrlBody defines model for PresignedUrlBody.
type PresignedUrlBody struct {
	ObjectName string `json:"ObjectName"`
	Parts      int    `json:"Parts"`
}

// PresignedUrlResp defines model for PresignedUrlResp.
type PresignedUrlResp struct {
	UploadID string   `json:"UploadID"`
	Urls     []string `json:"Urls"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Loc  []ValidationErrorLocInner `json:"loc"`
	Msg  string                    `json:"msg"`
	Type string                    `json:"type"`
}

// ValidationErrorLocInner defines model for ValidationError_loc_inner.
type ValidationErrorLocInner struct {
	union json.RawMessage
}

// ValidationErrorLocInner0 defines model for .
type ValidationErrorLocInner0 = string

// ValidationErrorLocInner1 defines model for .
type ValidationErrorLocInner1 = int

// AbortMultipartUploadJSONRequestBody defines body for AbortMultipartUpload for application/json ContentType.
type AbortMultipartUploadJSONRequestBody = AbortUploadBody

// CompleteUploadJSONRequestBody defines body for CompleteUpload for application/json ContentType.
type CompleteUploadJSONRequestBody = CompleteUploadBody

// GetPresignedUrlsJSONRequestBody defines body for GetPresignedUrls for application/json ContentType.
type GetPresignedUrlsJSONRequestBody = PresignedUrlBody

// AsValidationErrorLocInner0 returns the union data inside the ValidationErrorLocInner as a ValidationErrorLocInner0
func (t ValidationErrorLocInner) AsValidationErrorLocInner0() (ValidationErrorLocInner0, error) {
	var body ValidationErrorLocInner0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLocInner0 overwrites any union data inside the ValidationErrorLocInner as the provided ValidationErrorLocInner0
func (t *ValidationErrorLocInner) FromValidationErrorLocInner0(v ValidationErrorLocInner0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLocInner0 performs a merge with any union data inside the ValidationErrorLocInner, using the provided ValidationErrorLocInner0
func (t *ValidationErrorLocInner) MergeValidationErrorLocInner0(v ValidationErrorLocInner0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorLocInner1 returns the union data inside the ValidationErrorLocInner as a ValidationErrorLocInner1
func (t ValidationErrorLocInner) AsValidationErrorLocInner1() (ValidationErrorLocInner1, error) {
	var body ValidationErrorLocInner1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLocInner1 overwrites any union data inside the ValidationErrorLocInner as the provided ValidationErrorLocInner1
func (t *ValidationErrorLocInner) FromValidationErrorLocInner1(v ValidationErrorLocInner1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLocInner1 performs a merge with any union data inside the ValidationErrorLocInner, using the provided ValidationErrorLocInner1
func (t *ValidationErrorLocInner) MergeValidationErrorLocInner1(v ValidationErrorLocInner1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationErrorLocInner) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationErrorLocInner) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// AbortMultipartUploadWithBody request with any body
	AbortMultipartUploadWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AbortMultipartUpload(ctx context.Context, body AbortMultipartUploadJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CompleteUploadWithBody request with any body
	CompleteUploadWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CompleteUpload(ctx context.Context, body CompleteUploadJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPresignedUrlsWithBody request with any body
	GetPresignedUrlsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GetPresignedUrls(ctx context.Context, body GetPresignedUrlsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateNewServiceToken request
	CreateNewServiceToken(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) AbortMultipartUploadWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAbortMultipartUploadRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AbortMultipartUpload(ctx context.Context, body AbortMultipartUploadJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAbortMultipartUploadRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CompleteUploadWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCompleteUploadRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CompleteUpload(ctx context.Context, body CompleteUploadJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCompleteUploadRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPresignedUrlsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPresignedUrlsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPresignedUrls(ctx context.Context, body GetPresignedUrlsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPresignedUrlsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateNewServiceToken(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateNewServiceTokenRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewAbortMultipartUploadRequest calls the generic AbortMultipartUpload builder with application/json body
func NewAbortMultipartUploadRequest(server string, body AbortMultipartUploadJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAbortMultipartUploadRequestWithBody(server, "application/json", bodyReader)
}

// NewAbortMultipartUploadRequestWithBody generates requests for AbortMultipartUpload with any type of body
func NewAbortMultipartUploadRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/s3/abortMultipartUpload")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCompleteUploadRequest calls the generic CompleteUpload builder with application/json body
func NewCompleteUploadRequest(server string, body CompleteUploadJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCompleteUploadRequestWithBody(server, "application/json", bodyReader)
}

// NewCompleteUploadRequestWithBody generates requests for CompleteUpload with any type of body
func NewCompleteUploadRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/s3/completeUpload")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetPresignedUrlsRequest calls the generic GetPresignedUrls builder with application/json body
func NewGetPresignedUrlsRequest(server string, body GetPresignedUrlsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGetPresignedUrlsRequestWithBody(server, "application/json", bodyReader)
}

// NewGetPresignedUrlsRequestWithBody generates requests for GetPresignedUrls with any type of body
func NewGetPresignedUrlsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/s3/presignedUrls")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateNewServiceTokenRequest generates requests for CreateNewServiceToken
func NewCreateNewServiceTokenRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/token")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// AbortMultipartUploadWithBodyWithResponse request with any body
	AbortMultipartUploadWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AbortMultipartUploadResponse, error)

	AbortMultipartUploadWithResponse(ctx context.Context, body AbortMultipartUploadJSONRequestBody, reqEditors ...RequestEditorFn) (*AbortMultipartUploadResponse, error)

	// CompleteUploadWithBodyWithResponse request with any body
	CompleteUploadWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CompleteUploadResponse, error)

	CompleteUploadWithResponse(ctx context.Context, body CompleteUploadJSONRequestBody, reqEditors ...RequestEditorFn) (*CompleteUploadResponse, error)

	// GetPresignedUrlsWithBodyWithResponse request with any body
	GetPresignedUrlsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GetPresignedUrlsResponse, error)

	GetPresignedUrlsWithResponse(ctx context.Context, body GetPresignedUrlsJSONRequestBody, reqEditors ...RequestEditorFn) (*GetPresignedUrlsResponse, error)

	// CreateNewServiceTokenWithResponse request
	CreateNewServiceTokenWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*CreateNewServiceTokenResponse, error)
}

type AbortMultipartUploadResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *AbortUploadResp
	JSON422      *HTTPValidationError
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r AbortMultipartUploadResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AbortMultipartUploadResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CompleteUploadResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *CompleteUploadResp
	JSON422      *HTTPValidationError
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r CompleteUploadResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CompleteUploadResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPresignedUrlsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *PresignedUrlResp
	JSON422      *HTTPValidationError
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r GetPresignedUrlsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPresignedUrlsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateNewServiceTokenResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *CreateServiceTokenResp
	JSON422      *HTTPValidationError
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r CreateNewServiceTokenResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateNewServiceTokenResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// AbortMultipartUploadWithBodyWithResponse request with arbitrary body returning *AbortMultipartUploadResponse
func (c *ClientWithResponses) AbortMultipartUploadWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AbortMultipartUploadResponse, error) {
	rsp, err := c.AbortMultipartUploadWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAbortMultipartUploadResponse(rsp)
}

func (c *ClientWithResponses) AbortMultipartUploadWithResponse(ctx context.Context, body AbortMultipartUploadJSONRequestBody, reqEditors ...RequestEditorFn) (*AbortMultipartUploadResponse, error) {
	rsp, err := c.AbortMultipartUpload(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAbortMultipartUploadResponse(rsp)
}

// CompleteUploadWithBodyWithResponse request with arbitrary body returning *CompleteUploadResponse
func (c *ClientWithResponses) CompleteUploadWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CompleteUploadResponse, error) {
	rsp, err := c.CompleteUploadWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCompleteUploadResponse(rsp)
}

func (c *ClientWithResponses) CompleteUploadWithResponse(ctx context.Context, body CompleteUploadJSONRequestBody, reqEditors ...RequestEditorFn) (*CompleteUploadResponse, error) {
	rsp, err := c.CompleteUpload(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCompleteUploadResponse(rsp)
}

// GetPresignedUrlsWithBodyWithResponse request with arbitrary body returning *GetPresignedUrlsResponse
func (c *ClientWithResponses) GetPresignedUrlsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GetPresignedUrlsResponse, error) {
	rsp, err := c.GetPresignedUrlsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPresignedUrlsResponse(rsp)
}

func (c *ClientWithResponses) GetPresignedUrlsWithResponse(ctx context.Context, body GetPresignedUrlsJSONRequestBody, reqEditors ...RequestEditorFn) (*GetPresignedUrlsResponse, error) {
	rsp, err := c.GetPresignedUrls(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPresignedUrlsResponse(rsp)
}

// CreateNewServiceTokenWithResponse request returning *CreateNewServiceTokenResponse
func (c *ClientWithResponses) CreateNewServiceTokenWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*CreateNewServiceTokenResponse, error) {
	rsp, err := c.CreateNewServiceToken(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateNewServiceTokenResponse(rsp)
}

// ParseAbortMultipartUploadResponse parses an HTTP response from a AbortMultipartUploadWithResponse call
func ParseAbortMultipartUploadResponse(rsp *http.Response) (*AbortMultipartUploadResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AbortMultipartUploadResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest AbortUploadResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCompleteUploadResponse parses an HTTP response from a CompleteUploadWithResponse call
func ParseCompleteUploadResponse(rsp *http.Response) (*CompleteUploadResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CompleteUploadResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest CompleteUploadResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetPresignedUrlsResponse parses an HTTP response from a GetPresignedUrlsWithResponse call
func ParseGetPresignedUrlsResponse(rsp *http.Response) (*GetPresignedUrlsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPresignedUrlsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest PresignedUrlResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateNewServiceTokenResponse parses an HTTP response from a CreateNewServiceTokenWithResponse call
func ParseCreateNewServiceTokenResponse(rsp *http.Response) (*CreateNewServiceTokenResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateNewServiceTokenResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest CreateServiceTokenResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZXXPUOhL9KyrtPnqYSUKyMG8hZCEshBQzWapuKpXSSO2xwJaMJCdMpea/35Lkb8tJ",
	"IIS6D7yQsdxqdZ8+OmqLW0xllksBwmg8v8WaJpAR9/NwJZU5z1NJ2CvJNnYIvpMsT8H+/Lj6AtSckgzw",
	"vP0QYT/l5DWeNz+3Ec6VzEEZDro//RYbbtLGj/B+zCa3Y9ooLtbWQ+O4meHHOBvabyOs4FvBFTA8vxgJ",
	"8TKqPfXT3UbtoU+g8x4CH0BrsrZTFwWlAAxsFI/EpXbapFgNBRD5h6AY1TGG8XTgbSN8JC12Bs6IMj0w",
	"jxKgX3WRLd4e7u4f4Hl/IMLHS7LGc/8nwtbFaZGtQOH5bIBi31uTafVGJ8S7HeDj12lmHBu34MCuHUFj",
	"bUeFH63ncGFgDWoAZjjFjucWnh3wWmCO7tD7IR3nql1E4/nFowvzWAeXD9w3j6n4z+yiEqBbzA1k7se/",
	"FcR4jv81bQR1WqrptF+7Nlt0454oRTaP3qN3lTmqlwxJYIBSA6IFhPB/sOnz572kxHAp8BwnxuTz6TTj",
	"gsupdEbD8jkXTa72MQB647Uxrcfug6VlaN2Ppl2LlQJiYAHqmlNYyq8gqtS7oRNKQesrYy3sMwNNFc/L",
	"7JcJoHefl8hbIW8VSA2+51yBvuIjPlihXPSIC6SBSsE0Mgl0/CKu0TVJOUOxtPJTl2hvNhuKUYSFNJMV",
	"xFLBJJcpp5vA0jwDbUiWI5MQg7hgnBIDfm3DM0DeAbpJOE3cqM02K7RBQhq08hHmBlxQKFfSxmuTbsUX",
	"jE5BrEAnVz+LTDn/Hmh2XszuXP2esnYWCdVVU5nDcP5RSnhmIybODYOYixJVDQbJGOWgMq41l0Ijqao6",
	"K75OjEZrRYRx7UadCIaM8NQCHPM0KFkanLsrbYgJhLTwr9HJ6whxBsLwmIPydS8E/1ZAukGW9GWU3tpI",
	"T8PCJHaKJQdDhQbVjY3u7eyx/5AJi1+yyfO9l7PJi4N9mNADdjA72Nk/iBkNhexgvfLD/XhfAVG9Zeqh",
	"u5Wgs2P7pW7rQlgBthF+u1ye/d/SyTHvWCmpeprIwBCeuhM0ldSu2rO/SiW94kK4eMffXUY40/Z0tP/W",
	"ibk/9nB9Mt+XA4muMnrgkdeHp3XqlZ76x17LIoTvNsInwoASJK0B70ZIJQvw5BDpHCiPOUVg5yFrVikZ",
	"F2vHX//GxROgoQ9YB3wzxu1PkiIqhYHvxu5VLmKpMi9KZCUL0ywR8p41LX8/8qTIiJgoIIysUkClpd3k",
	"15zZ2DOrvWV4D1nLVHoeljSn6DcJiBYoktJCKSc2Pi1bQWJgYo3v3WuuJk2Ol7V90wmcKdB8LYCdq/SH",
	"PjTLHmz2Sz4u64bONipZkeH5zmifNtbQB6Jryckgz17ugc4q1PpG+FxZLl74v+XjcL/+WA9ZeW3t7gB5",
	"Si9+3cHubUPRD3cEh0pQ7xbTp1PQHmZuoZ8TuNaKLaisw2F77+J50Ad+dfTVH6NuSy6DOtWrgF+6lXSr",
	"BAFtHU/H9rhi8zF2h1k/wtvBnhhfpg2R60doobjZLCygHn9/gB8WJrFPK/f030p03n1e4shfUFnnq95h",
	"b78z8NY6tvo71LdPx4slOjw7QSBYLrkwpYyCKjvTkpVosYcKx15EBENE0YRfW629keprnMobZENgReqb",
	"2Loyy7d/oUNnDAqVTQOO8DUo7QOYPdt5NrNQyxwEyTme4z03FOGcmMQBMNV7U7KSynwoUsNzUt2guMNO",
	"andrYgnrQD1h1TVL39ozAbSp9NSdTsJNJ3mecv8pNP2i/ceU5/R9jB/ckHUpZ1QBbkDnUmhf0N3ZzlMs",
	"72Vj647mzolpTVBWoVHVsQQDmEX/+e7uLwsp2KcMw2pMUL3f9mezXxZGty8KBFAZOF6CqqKwm7DIMqI2",
	"NXY1k1BNJUPW7rjJW7ptD5xt5OhKO1/P40TtfmU/EUVDNxi/l6Why4RhQfxbVGH3h5h3ELNC9MGM7A6P",
	"EvINmLOO5dNQctj2/V5CDtutYRlqG3T+6b1G1H34/iHlHaR8Awa1UCs74jt4WV8kjaijg/wUbtrXDfgp",
	"dWrkcmMIR2mDnNEfboxyo2xnXZu8oPyIGN/IXlzanrilZw5BdAo3qANti0Daj1dXUtuB/3ajXPp38fj/",
	"sylUiud4ireX278DAAD//y+L8prgHQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
