name: goreleaser

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

env:
  NUGET_SOURCE_URL: "https://nuget.pkg.github.com/swissopenem/index.json" 
  # For deploying within ETHZ w/o authorization that is required for public github access
  GITLAB_SOURCE_URL: "https://sissource.ethz.ch/api/v4/projects/1201/packages/nuget/index.json"

jobs:
  goreleaser:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x.x 

      # AI Generated step to parse the version
      - name: Extract version from Git tag
        id: extract_version
        run: |
          VERSION=${GITHUB_REF##*/} 
          echo "VERSION=${VERSION/v/}" >> $GITHUB_ENV

      - name: Create NuGet package
        run: |
          nuget pack openem-ingestor.nuspec -version ${{env.VERSION}} 

      - name: Publish NuGet package to GitHub
        run: |
          nuget push *.nupkg -Source "${{env.NUGET_SOURCE_URL}}" -ApiKey ${{ secrets.GITHUB_TOKEN }}
          nuget push *.nupkg -Source "${{env.GITLAB_SOURCE_URL}}" -ApiKey ${{ secrets.SISSOURCE_GITLAB_NUGET_REPO }} 


  build_docker_image_release:
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/ci.yaml
  # goreleaser-darwin:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v6
  #       with:
  #         fetch-depth: 0
  #     - name: Set up Go
  #       uses: actions/setup-go@v5
  #       with:
  #         go-version: stable

  #     - name: Set up Wails
  #       run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
        
  #     - name: Run GoReleaser
  #       uses: goreleaser/goreleaser-action@v6
  #       with:
  #         distribution: goreleaser
  #         version: latest
  #         args: release --clean --config .goreleaser_macos.yaml
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}